#!/usr/bin/env python3
"""
Test CloudFormation template syntax generated by the App Runner workflow.
"""
import os
import subprocess
import tempfile
import yaml
import pytest


def test_apprunner_workflow_cloudformation_syntax():
    """Test that the CloudFormation template generated by the workflow has valid syntax."""
    
    # Set up environment variables similar to what the workflow would have
    test_env = {
        'AWS_REGION': 'us-east-1',
        'ECR_REGISTRY': '123456789012.dkr.ecr.us-east-1.amazonaws.com',
        'ECR_REPOSITORY': 'friday-app',
        'APP_RUNNER_SERVICE_NAME': 'friday-service',
        'APP_RUNNER_PORT': '5000'
    }
    
    # The CloudFormation template from the workflow (with intrinsic functions as strings for testing)
    template_content = '''AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AppRunnerECRAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "${AWS::StackName}-AppRunnerECRAccessRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
  Svc:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: friday-service
      SourceConfiguration:
        AutoDeploymentsEnabled: true
        ImageRepository:
          ImageIdentifier: 123456789012.dkr.ecr.us-east-1.amazonaws.com/friday-app:abc123
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: '5000'
            RuntimeEnvironmentVariables:
              - Name: AUTO_START
                Value: 'true'
              - Name: APP_VERSION
                Value: 'abc123'
        AuthenticationConfiguration:
          AccessRoleArn: "AppRunnerECRAccessRole.Arn"
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /healthz
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 3
Outputs:
  ServiceUrl:
    Value: "Svc.ServiceUrl"'''
    
    # Parse the YAML to ensure it's syntactically valid
    try:
        parsed = yaml.safe_load(template_content)
        assert parsed is not None
        assert 'AWSTemplateFormatVersion' in parsed
        assert 'Resources' in parsed
        assert 'AppRunnerECRAccessRole' in parsed['Resources']
        assert 'Svc' in parsed['Resources']
        assert 'Outputs' in parsed
        
        # Check that the App Runner service references the correct role
        svc = parsed['Resources']['Svc']
        auth_config = svc['Properties']['SourceConfiguration']['AuthenticationConfiguration']
        assert 'AppRunnerECRAccessRole.Arn' in auth_config['AccessRoleArn']
        
        # Check that the role has the correct managed policy
        role = parsed['Resources']['AppRunnerECRAccessRole']
        managed_policies = role['Properties']['ManagedPolicyArns']
        assert 'arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess' in managed_policies
        
        # Check that the role has the correct trust policy
        trust_policy = role['Properties']['AssumeRolePolicyDocument']
        statements = trust_policy['Statement']
        assert len(statements) == 1
        assert statements[0]['Principal']['Service'] == 'build.apprunner.amazonaws.com'
        
        print("CloudFormation template syntax validation passed")
        
    except yaml.YAMLError as e:
        pytest.fail(f"Invalid YAML syntax in CloudFormation template: {e}")
    except KeyError as e:
        pytest.fail(f"Missing required key in CloudFormation template: {e}")
    except Exception as e:
        pytest.fail(f"Unexpected error validating CloudFormation template: {e}")


def test_workflow_validation_logic():
    """Test the validation logic used in the workflow."""
    
    # Test that validation fails when required variables are missing
    required_vars = ['AWS_REGION', 'AWS_ROLE_DEPLOY', 'ECR_REPOSITORY', 'APP_RUNNER_STACK_NAME', 'APP_RUNNER_SERVICE_NAME']
    
    for var in required_vars:
        # Create environment with one variable missing
        test_env = {
            'AWS_REGION': 'us-east-1',
            'AWS_ROLE_DEPLOY': 'arn:aws:iam::123456789012:role/GitHubOIDC',
            'ECR_REPOSITORY': 'friday-app',
            'APP_RUNNER_STACK_NAME': 'friday-stack',
            'APP_RUNNER_SERVICE_NAME': 'friday-service'
        }
        del test_env[var]
        
        # Create a temporary script to test validation
        validation_script = f'''#!/bin/bash
set -e
AWS_REGION="{test_env.get('AWS_REGION', '')}"
AWS_ROLE_DEPLOY="{test_env.get('AWS_ROLE_DEPLOY', '')}"
ECR_REPOSITORY="{test_env.get('ECR_REPOSITORY', '')}"
APP_RUNNER_STACK_NAME="{test_env.get('APP_RUNNER_STACK_NAME', '')}"
APP_RUNNER_SERVICE_NAME="{test_env.get('APP_RUNNER_SERVICE_NAME', '')}"

# Check required variables (same logic as workflow)
if [ -z "$AWS_REGION" ]; then
  echo "ERROR: AWS_REGION is required"
  exit 1
fi
if [ -z "$AWS_ROLE_DEPLOY" ]; then
  echo "ERROR: AWS_ROLE_DEPLOY is required"
  exit 1
fi
if [ -z "$ECR_REPOSITORY" ]; then
  echo "ERROR: ECR_REPOSITORY is required"
  exit 1
fi
if [ -z "$APP_RUNNER_STACK_NAME" ]; then
  echo "ERROR: APP_RUNNER_STACK_NAME is required"
  exit 1
fi
if [ -z "$APP_RUNNER_SERVICE_NAME" ]; then
  echo "ERROR: APP_RUNNER_SERVICE_NAME is required"
  exit 1
fi
'''
        
        # Use a unique temporary file name for each test
        script_path = f'/tmp/validate_{var}.sh'
        with open(script_path, 'w') as f:
            f.write(validation_script)
            
        try:
            # Make executable and run
            os.chmod(script_path, 0o755)
            result = subprocess.run([script_path], capture_output=True, text=True)
            
            # Should fail when required variable is missing
            assert result.returncode != 0, f"Validation should fail when {var} is missing"
            assert f"ERROR: {var} is required" in result.stdout, f"Should report missing {var}"
            
        finally:
            if os.path.exists(script_path):
                os.unlink(script_path)
    
    print("Workflow validation logic test passed")


def test_ecr_registry_computation():
    """Test ECR registry computation logic."""
    
    # Test script that simulates the ECR registry computation
    computation_script = '''#!/bin/bash
set -e

# Simulate aws sts get-caller-identity
ACCOUNT_ID="123456789012"
AWS_REGION="us-east-1"
ECR_REGISTRY=""

# Compute ECR_REGISTRY if not provided (same logic as workflow)
if [ -z "$ECR_REGISTRY" ]; then
  ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
  echo "Computed ECR_REGISTRY: $ECR_REGISTRY"
else
  echo "Using provided ECR_REGISTRY: $ECR_REGISTRY"
fi

echo "$ECR_REGISTRY"
'''
    
    script_path = '/tmp/compute_ecr.sh'
    with open(script_path, 'w') as f:
        f.write(computation_script)
        
    try:
        # Make executable and run
        os.chmod(script_path, 0o755)
        result = subprocess.run([script_path], capture_output=True, text=True)
        
        # Should succeed and output the computed registry
        assert result.returncode == 0, "ECR registry computation should succeed"
        expected = "123456789012.dkr.ecr.us-east-1.amazonaws.com"
        assert expected in result.stdout, f"Should compute correct ECR registry: {expected}"
        
    finally:
        if os.path.exists(script_path):
            os.unlink(script_path)
    
    print("ECR registry computation test passed")


if __name__ == "__main__":
    test_apprunner_workflow_cloudformation_syntax()
    test_workflow_validation_logic()
    test_ecr_registry_computation()
    print("All tests passed!")